# ✅ CORRECTO - Sintaxis Windows
version: '3.9'
services:
  microservicio:
    image: ministerio_envio_rips:latest
    build: .
    volumes:
      - C:/Users/lsanc/Desktop/Json_enviar:/app/Json_enviar

    environment:
      - NODE_ENV=development
      - MODO_EJECUCION=continuo
      - RUTA_ARCHIVOS_GENERADOS=/app/Json_enviar/porEnviar
      - RUTA_ARCHIVOSENVIADOS=/app/Json_enviar/procesados
      - RUTA_ARCHIVOSRECHAZADOS=/app/Json_enviar/rechazados
      - RUTA_BASE_CARPETAS=/app/Json_enviar
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - fevrips-net

networks:
  fevrips-net:
    external: true
    name: dockerministerio_salud_fevrips-net