# ✅ CORRECTO - Sintaxis Windows
version: '3.9'
services:
  microservicio:
    image: lorve10/ministerio_envio_rips:v2 
    build: .
    volumes:
      - C:/Users/USER/Desktop/Json_enviar/porEnviar:/app/porEnviar
      - C:/Users/USER/Desktop/Json_enviar/procesados:/app/procesados
      - C:/Users/USER/Desktop/Json_enviar/rechazados:/app/rechazados
      - C:/Users/USER/Desktop/Json_enviar:/app/Json_enviar

    environment:
      - NODE_ENV=development
      - MODO_EJECUCION=continuo
      - RUTA_ARCHIVOS_GENERADOS=/app/porEnviar
      - RUTA_ARCHIVOSENVIADOS=/app/procesados
      - RUTA_ARCHIVOSRECHAZADOS=/app/rechazados
      - RUTA_BASE_CARPETAS=/app/Json_enviar
    ports:
      - "3000:3000"